[tool.poetry]
name = "evnex-ha"
version = "0.3.2"
description = ""
authors = ["Brian Thorne <brian@thorne.link>"]

[tool.poetry.dependencies]
python = "^3.10"
homeassistant = "^2023.11"
evnex = "^0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
