name: "Validation And Formatting"
on:
  push:
  pull_request:

jobs:
  lint:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        uses: chartboost/ruff-action@v1

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Download repo
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.11"
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            ~/.cache/pip
          key: custom-component-ci
      - uses: "home-assistant/actions/hassfest@master"
      - uses: hacs/action@main
        with:
          CATEGORY: integration
